# Workflow
name: upload-artifact-sample

on:
  # 発動条件 ボタンを押下した時
  push:
    workflow_dispatch:

# JOB
jobs:
  artifact-sample:
    runs-on: self-hosted
    steps:
      # 成果用としてアップロードするファイルを作成
      - name: artifact output
        id: rnd
        run: |
                    echo "Hello, World" > hello.txt
      # 成果物アップロード
      - name: artifact upload
        uses: actions/upload-artifact@v2.2.0
        with:
          # 保存ファイル名（name.zip）
          name: hello
          # 保存するファイル
          path: hello.txt
          # 保存期間（日）
          retention-days: 3

