name: clone_test

on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: clone sh
               run: sh ./clone.sh    
    
    
    
    
    
    
    
    

