#ymlファイル

name: clone_test

on:
  workflow_dispatch:

jobs:
    build:
        name: clone
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: clone sh
              run: sh ./clone.sh   
