#ymlファイル

name: clone_test

on:
  workflow_dispatch:

jobs:
    build:
        name: clone
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: clone action
              run: sh ./clone.sh   
