name: sample

on:
  schedule:
    - cron: '*/10 * * * *'
      workflow_disapatch:

        jobs:
          test:
            runs-on: ubuntu-latest
            steps:
              - run: echo "hello"
