name: Announce
on:
  schedule:
    - cron: "0 0 * * *" # 毎日9時(JST)
jobs:
  announce:
    runs-on: ubuntu-latest
    steps:
      - id: count
        run: |
          pr_count=$(gh pr list -s open --json number --jq length)
          echo "pr_count=$pr_count" >> $GITHUB_OUTPUT 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "今朝のPRは${{ steps.count.outputs.pr_count }}件です"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
