name: time

on:
  schedule:
     - cron: "0 0 * * *"
       workflow_dispatch:

         jobs:
           execute:
             runs-on: ubuntu-latest

             steps:
                - name: Print date
                  run: 
                     echo $(date '+%Y-%m-%d %H:%M:%S(%z)')
                  echo $(TZ=Asia/Tokyo date '+%Y-%m-%d %H:%M:%S(%z)')
